apiVersion: batch/v1
kind: Job
metadata:
  name: jobs2
spec:
  template:
    spec:
      containers:
      - name: cataniedataload
        image: garethcmurphy/cataniedataload
        imagePullPolicy: Always
        command: ["yarn","run", "send"]
        volumeMounts:
        - name: foo
          mountPath: "/tmp/config.json"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: db-user-pass
      restartPolicy: Never
  backoffLimit: 1
